name: Sync Postman Collection

on:
  push:
    paths:
      - "Postman Collections/collections.json"  # Matches your repo structure
    branches:
      - main  # Change this if using a different branch

jobs:
  update_postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Postman Collection
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          COLLECTION_ID="your_collection_id_here"
          FILE_PATH="Postman Collections/collections.json"

          curl --location --request PUT "https://api.getpostman.com/collections/ed61b0fd-dcfb-4b42-9961-ca7b3bf4ede1" \
          --header "X-API-Key: $POSTMAN_API_KEY" \
          --header "Content-Type: application/json" \
          --data @"$FILE_PATH"
