name: Sync & Test Postman Collection

on:
  push:
    paths:
      - "Postman Collections/collections.json"
      - ".github/workflows/postman-sync.yml"

jobs:
  update-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare JSON Payload
        env:
          FILE_PATH: "Postman Collections/collections.json"
        run: |
          jq 'del(.auth) | { collection: . }' "$FILE_PATH" > wrapped_collection.json

      - name: Send Updated Collection to Postman
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          COLLECTION_ID: "ed61b0fd-dcfb-4b42-9961-ca7b3bf4ede1"
        run: |
          curl --location --request PUT "https://api.getpostman.com/collections/$COLLECTION_ID" \
          --header "X-API-Key: $POSTMAN_API_KEY" \
          --header "Content-Type: application/json" \
          --data @wrapped_collection.json

  run-api-tests:
    runs-on: ubuntu-latest
    needs: update-postman
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run "Postman Collections/collections.json" \
            --reporters cli,junit \
            --reporter-junit-export results.xml --suppress-exit-code || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-results-xml
          path: results.xml
